### ISSUE TITLE
for named anonymous mappings, stackwalker output should drop ]

### ISSUE THREAD

**Issue by willkg** [rust-minidump/rust-minidump#1038]
In [bug 1926077](https://bugzilla.mozilla.org/show_bug.cgi?id=1926077), we're seeing crash reports where the stackwalker output for the module field is `base.art]`. That messes with signature generation plus it doesn't make any sense.

Example crash report: https://crash-stats.mozilla.org/report/index/4c36561c-ef1e-4a90-aea7-c79b60241020

```json
        {
          "file": null,
          "frame": 4,
          "function": null,
          "function_offset": null,
          "inlines": null,
          "line": null,
          "missing_symbols": true,
          "module": "base.art]",
          "module_offset": "0x0025c1ee",
          "offset": "0xba64b1ee",
          "trust": "scan",
          "unloaded_modules": null
        },
```

In these cases, the stackwalker should output something like `base.art` instead of `base.art]`.

This is with rust-minidump v0.22.2.

**Comment by gabrielesvelto** [comment]
Thanks for opening this @willkg. Given these are anonymous mappings I think we should extract the entire label and remove the square brackets.

**Comment by gabrielesvelto** [comment]
As it turns out there's two sides of this problem. The first one is that **minidump-writer** is misinterpreting the anonymous memory label as a file path (which is actually reasonable behavior since it kinda looks like a path). So the module name in the minidump is `/apex/com.android.art/javalib/boot.art]`, what happens next is that **rust-minidump** logic also treats the path as a literal path and picks up the last part of it verbatim, including the trailing square bracket. I'll open an issue in the **minidump-writer** repo and close this one because the stackwalker is basically just doing what it's being told to do and its behavior is not incorrect.

**Comment by gabrielesvelto** [comment]
See https://github.com/rust-minidump/minidump-writer/issues/139
