### ISSUE TITLE
Implement a simple crash address bitflip check

### ISSUE THREAD

**Issue by Gankra** [rust-minidump/rust-minidump#429]
This is a much more constrained version of https://github.com/luser/rust-minidump/issues/204

Gabriele originally described it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1738651

Essentially, the idea is to take the [crash address](https://github.com/luser/rust-minidump/blob/891fb8b1b0c80cf9cea4cff4476e9e75c515d176/minidump-processor/src/process_state.rs#L169) and apply an analysis which will result in us outputting an extra crash_might_be_a_bitflip flag (or whatever):

1. If the crash address points into mapped memory, assume there's no bitflip
2. otherwise, for every bit in the crash address:
3. flip the bit. If it is now null or points into mapped memory, assume it's a bitflip.

This would ideally use UnifiedMemoryInfo so that we're not relying on just the pages we actually have the memory info for.

This can be refined and tuned more based on experimentation and implementation experience.

**Comment by Gankra** [comment]
(I think this would be good for beginners but I haven't thought about it too much. I should really finish and land #263 as an example for adding a new "analysis" to minidump-processor.)

**Comment by Gankra** [comment]
Some potentially interesting refinements/issues:

* The crash address may *either* be an address that was trying to be executed or memory that was trying to be accessed. It's possible we want to treat the two different. 
  * MemoryInfo *does* have information about whether pages are executable, but this is a difficult signal to use in a program with a JIT because best-practice is to enforce W^X on JIT pages. This means functions on the stack may legitimately be "executing" non-executable pages at the time the minidump is generated. It's possible we can work with JIT at crashtime to resolve this but eugh.

* null pointer accesses are organically often "nearly null", which means perfectly normal execution can try to access "null with a bit flipped". i.e. if you load a field at offset 0x8 of a struct through a null pointer, we will actually load 0x8. Possibly this can be handled by conservatively assuming it's not a bitflip if the flipped bit is low (significantly less likely to be accessing exactly null+1MB or whatever).

* Maybe you want to have a more fuzzy signal than "true/false" like "likely/maybe/unlikely" but the problem with that system is that it's not at all clear *what* someone is supposed to do with that. I would rather develop something simple that's biased to keeping the signal/noise ratio high (i.e. something which only flags very likely bitflips). While a fuzzy system feels *appealing* at first, you need to recognize it in the context of an environment where you're getting thousands or millions of crash reports every day. Even with dedicated Crash Report Investigators, there are far too many crash reports to even investigate a small percentage of them. Bulk searches and bucketing is the name of the game, so any signal that has a lot of noise will very quickly be ignored.

**Comment by luser** [comment]
I've probably pointed you at this before, but there's some prior art in the [jit-crash-categorize](https://github.com/mozilla-services/minidump-stackwalk/blob/634f9624f5583521e79039e9d29b498f971a4fb4/minidump-stackwalk/jit-crash-categorize.cc) tool. dvander and I collaborated on it originally, and it looks like dmajor did some follow-up work on it. The intent was to run it as a deeper analysis specifically on crashes where the topmost symbolicated frame pointed to the JIT entry function, since the bucket of "crashes in JIT code" was too broad to be useful.

**Comment by Gankra** [comment]
Oh weird, why did no one complain that I didn't port this. Was it never turned on?

**Comment by gabrielesvelto** [comment]
This might be tuned to be crash-type specific in order to reduce the number of false positives, for example:
* On Windows only addresses from `EXCEPTION_ACCESS_VIOLATION_READ` and `EXCEPTION_ACCESS_VIOLATION_READ` crashes should be validated against non-executable pages
* Similarly, addresses from `EXCEPTION_ACCESS_VIOLATION_EXEC`, `EXCEPTION_ILLEGAL_INSTRUCTION` or `EXCEPTION_PRIV_INSTRUCTION` crashes should be validated against executable pages
* On Linux we'd have to check addresses for `SIGSEGV` and `SIGBUS` crashes against non-executable pages, and `SIGILL` ones against executable ones
* And on macOS I think it's going to be `EXC_BAD_ACCESS` and `EXC_BAD_INSTRUCTION` respectively, but I have to check if you can get some form of `EXC_BAD_ACCESS` exception if you try to execute code from unmapped or non-executable pages.

Either way this can be done in a follow-up.

**Comment by nbp** [comment]
> Oh weird, why did no one complain that I didn't port this. Was it never turned on?

@Gankra most likely because JIT crashes are hardly actionable, and that the last hand-made analysis done by Jan De Mooij were that most of these crashes were caused by corrupted code buffers.

Also, in the past, the JIT was blamed each time the stack ended in `???`, where the stack walker failed to find a frame. I think nowadays that we no longer display these crashes, or that the stack walker does a better job at inferring a nearby frame.

>     * null pointer accesses are organically often "nearly null", which means perfectly normal execution can try to access "null with a bit flipped". i.e. if you load a field at offset 0x8 of a struct through a null pointer, we will actually load 0x8. Possibly this can be handled by conservatively assuming it's not a bitflip if the flipped bit is low (significantly less likely to be accessing exactly null+1MB or whatever).

In the past, I did a bit of investigation on null-pointer accesses, and made a search query which [lookup crash reports by crash addresses which are null pointers except for the last 3 hexadecimal digits](https://crash-stats.mozilla.org/api/SuperSearch/?address=%400x[0]%2B[8421][0]%2B[a-f0-9][a-f0-9][a-f0-9]&date=%3E%3D2021-04-21T13%3A27%3A00.000Z&date=%3C2022-03-01T13%3A27%3A00.000Z&_histogram.date=product&_histogram_interval.date=1d).

I do recall having compared the frequency of each nullptr+bit-flip, but I do not have a record of the outcome.

**Comment by willkg** [comment]
> Oh weird, why did no one complain that I didn't port this. Was it never turned on?

We had talked about jit-crash-categorize in November and I wrote up this issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1743704

I'm pretty sure there was some additional conversation about it, but I apparently didn't capture it in the bug comments.

If we don't need jit-crash-categorize or the implementation that Socorro is currently using isn't useful, I would like to remove it as soon as I can. It'll reduce Socorro CI/build time.

**Comment by luser** [comment]
For some background on `jit-crash-categorize` see:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1124241
- https://bugzilla.mozilla.org/show_bug.cgi?id=1268029 
- https://bugzilla.mozilla.org/show_bug.cgi?id=764223

**Comment by nbp** [comment]
`jit-crash-categorize` should probably be revisited before using it as a way to detect bit-flips. As commented in [Bug 1743704](https://bugzilla.mozilla.org/show_bug.cgi?id=1743704), it can output false positive cases. We should probably revisit it before using it as a way to detect bit-flips.
